name: Build Pico Firmware
on: push

jobs:
  build_uf2:
    runs-on: ubuntu-latest
    steps:
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'
      - run: git clone https://github.com/micropython/micropython.git micropython

      - name: uncomment MSC mode
        run: sed "s/\/\/ \#define/#define/g" -i mpconfigboard.h
        working-directory: ./micropython/ports/rp2/boards/PICO

      - run: cat mpconfigboard.h
        working-directory: ./micropython/ports/rp2/boards/PICO

      - run: make submodules
        working-directory: ./micropython/ports/rp2

      - run: make
        working-directory: ./micropython/ports/rp2
      - run: ls -a
        working-directory: ./micropython/ports/rp2/build-PICO
