name: Build Pico Firmware
on: push

jobs:
  typescript_build:
    runs-on: ubuntu-latest
    steps:
      - uses: fiam/arm-none-eabi-gcc@v1
      - run: git clone https://github.com/micropython/micropython.git /micropython

      - name: uncomment MSC mode
        run: sed "s/\/\/ \#define/#define/g" -i mpconfigboard.h
        working-directory: ./micropython/ports/rp2/boards/PICO

      - run: make submodules
        working-directory: ./micropython/ports/rp2

      - run: make
